/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Model.NguoiDung;
import Service.NDService;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ThuyVT
 */
public class QLND extends javax.swing.JFrame {
    List<NguoiDung> listND = new ArrayList<>();
    NDService service = new NDService();
    DefaultTableModel defaultTableModel = new DefaultTableModel();
   
    /**
     * Creates new form QLND
     */
    public QLND() {
        initComponents();
        
        // gan gia tri cho defaulTable Model
        defaultTableModel = (DefaultTableModel) tblListND.getModel();
        
        doDuLieu();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGRole = new javax.swing.ButtonGroup();
        btnGGioiTinh = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        rdoUser = new javax.swing.JRadioButton();
        rdoAdmin = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        rdoNam = new javax.swing.JRadioButton();
        rdoNu = new javax.swing.JRadioButton();
        rdoKhac = new javax.swing.JRadioButton();
        txtTaiKhoan = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtMatKhau = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        chkTrangThai = new javax.swing.JCheckBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblListND = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        cboViTriCv = new javax.swing.JComboBox<>();
        btnXuat = new javax.swing.JButton();
        btnNhap = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnSapXep = new javax.swing.JButton();
        btnTim = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("QUAN LY NGUOI DUNG");

        jLabel2.setText("Tai khoan");

        jLabel3.setText("Email");

        jLabel4.setText("Mat Khau");

        jLabel5.setText("Quyen");

        btnGRole.add(rdoUser);
        rdoUser.setText("Nguoi dung");

        btnGRole.add(rdoAdmin);
        rdoAdmin.setSelected(true);
        rdoAdmin.setText("Admin");

        jLabel6.setText("Gioi tinh");

        btnGGioiTinh.add(rdoNam);
        rdoNam.setSelected(true);
        rdoNam.setText("Nam");

        btnGGioiTinh.add(rdoNu);
        rdoNu.setText("Nu");

        btnGGioiTinh.add(rdoKhac);
        rdoKhac.setText("Gioi Tinh khac");

        jLabel7.setText("Trang thai");

        chkTrangThai.setText("Hoat dong ?");

        tblListND.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Tai khoan", "Email", "Mat khau", "Quyen", "Gioi tinh", "Trang thai", "Vi tri cong viec"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Boolean.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblListND.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblListNDMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblListND);

        jLabel8.setText("Vi tri cong viec");

        cboViTriCv.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sinh vien", "Giang vien", "Nhan vien" }));

        btnXuat.setText("Xuat");
        btnXuat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnXuatMouseClicked(evt);
            }
        });

        btnNhap.setText("Nhap");
        btnNhap.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnNhapMouseClicked(evt);
            }
        });
        btnNhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNhapActionPerformed(evt);
            }
        });

        btnSua.setText("Sua");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        btnXoa.setText("Xoa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        btnSapXep.setText("Sap xep");

        btnTim.setText("Tim");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(rdoUser, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(rdoAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(txtTaiKhoan)
                                            .addComponent(txtEmail, javax.swing.GroupLayout.DEFAULT_SIZE, 234, Short.MAX_VALUE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(18, 18, 18)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(chkTrangThai, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(rdoNam, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(rdoNu, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addComponent(rdoKhac, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(19, 19, 19)
                                                .addComponent(txtMatKhau)))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cboViTriCv, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(148, 148, 148)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnSapXep)
                            .addComponent(btnXuat)
                            .addComponent(btnNhap)
                            .addComponent(btnSua)
                            .addComponent(btnXoa)
                            .addComponent(btnTim))
                        .addGap(34, 34, 34))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtTaiKhoan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnXuat))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtMatKhau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(btnNhap)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnSua)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(rdoUser)
                            .addComponent(rdoAdmin))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(rdoNam)
                            .addComponent(rdoNu)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdoKhac)
                    .addComponent(btnTim))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(chkTrangThai))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(cboViTriCv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSapXep))
                .addGap(20, 20, 20)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnXuatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnXuatMouseClicked
        // TODO add your handling code here:
        doDuLieu();
    }//GEN-LAST:event_btnXuatMouseClicked

    private void btnNhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNhapActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btnNhapActionPerformed

    private void btnNhapMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNhapMouseClicked
        // TODO add your handling code here:
        // Neu kiem tra du lieu dung
        if (kiemTraDuLieu()) {
           NguoiDung nd = getDuLieuTuForm();
             
//             NguoiDung nd1 = new NguoiDung(txtTaiKhoan.getText(), 
//                     txtMatKhau.getText(), txtEmail.getText(), 
//                     rdoUser.isSelected() ? 1 : 2, chkTrangThai.isSelected(), 
//                     rdoNam.isSelected() ? "Nam" : rdoNu.isSelected() ? "Nu" : "Gioi tinh khac", 
//                     cboViTriCv.getSelectedItem().toString());

            service.add(nd);
            
            doDuLieu();
            
            JOptionPane.showMessageDialog(this, "Nhap du lieu thanh cong");
        }
    }//GEN-LAST:event_btnNhapMouseClicked

    private void tblListNDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblListNDMouseClicked
        // TODO add your handling code here:
        int rowIndex = tblListND.getSelectedRow();
        if (rowIndex >= 0 && rowIndex <= listND.size()) {
            doDuLieuLenForm(rowIndex);
        }
    }//GEN-LAST:event_tblListNDMouseClicked

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        // TODO add your handling code here:
        int rowSelected = tblListND.getSelectedRow();
        if (rowSelected >= 0) {
            // Lay gia tri moi tu form
            NguoiDung item = getDuLieuTuForm();
            // Update gia tri doi tuong moi vao DS
            service.update(item, rowSelected);
            // Do du lieu ds moi len bang
            doDuLieu();
        } else {
            JOptionPane.showMessageDialog(this, "Chon dong can sua");
        }
    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // TODO add your handling code here:
        if (tblListND.getSelectedRow() >= 0) {
            int result = JOptionPane.showConfirmDialog(this, "Ban co chac chan muon xoa ban ghi nay khong");
            // 0: co; 1: ko; 2: cancel
            System.out.println(result);
            if (result == 0) {
                // goi service de xoa du lieu
                service.delete(tblListND.getSelectedRow());
                // do du lieu len bang
                doDuLieu();
            }
        } else {
            JOptionPane.showMessageDialog(this, "Chon dong can xoa");
        }
    }//GEN-LAST:event_btnXoaActionPerformed
    private void doDuLieuLenForm(int rowIndex) {
            // Lay doi tuong nguoi dung tu index
           NguoiDung nd = listND.get(rowIndex);
           txtTaiKhoan.setText(nd.getTenTaiKhoan());
           txtEmail.setText(nd.getEmail());
           txtMatKhau.setText(nd.getMatKhau());
           
           if (nd.getQuyen() == 1) {
               rdoUser.setSelected(true);
           } else {
               rdoAdmin.setSelected(true);
           }
           // Set gia tri cho Radio
           if (nd.getGioiTinh().trim().equalsIgnoreCase("Nam")) {
               rdoNam.setSelected(true);
           } else if (nd.getGioiTinh().trim().equalsIgnoreCase("Nu")) {
               rdoNu.setSelected(true);
           } else {
               rdoKhac.setSelected(true);
           }
           // Set gia tri cho ComboBox
           cboViTriCv.setSelectedItem(nd.getViTriCV());
           // Set gia tri cho Check box
           chkTrangThai.setSelected(nd.isTrangThai());
    }
    private void doDuLieu() {
            // do du lieu tu dong dau tien
            defaultTableModel.setRowCount(0);     
            // gan gia tri cho list
            listND = service.getList();
        
            for (NguoiDung nd : listND) {
                defaultTableModel.addRow(new Object[] {nd.getTenTaiKhoan(), nd.getEmail(),
                    nd.getMatKhau(), nd.getQuyen() == 1 ? "Nguoi dung" : "Admin", nd.getGioiTinh(),
                    nd.isTrangThai(), nd.getViTriCV()});
            }
     }
     
     private boolean kiemTraDuLieu() {
            if (txtTaiKhoan.getText().trim().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Bat buoc nhap thong tin tai khoan");
                return false;
            } else if (txtEmail.getText().trim().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Bat buoc nhap email");
                return false;
            } else if (txtMatKhau.getText().trim().isEmpty()) {
                JOptionPane.showConfirmDialog(this, "Bat buoc nhap mat khau");
                return false;
            } 
            return true;
     }
     
     private NguoiDung getDuLieuTuForm() {
           NguoiDung nd = new NguoiDung();
            // Gan du lieu txtTaiKhoan cho thuoc tinh tentaikhoan
            nd.setTenTaiKhoan(txtTaiKhoan.getText());
            // Gan du lieu txtEmail cho thuoc tinh email
            nd.setEmail(txtEmail.getText());
            // Gan du lieu txtMatKhau cho thuoc tinh mk
            nd.setMatKhau(txtMatKhau.getText());
            // Gan du lieu quyen cho thuoc tinh quyen
            if (rdoUser.isSelected()) {
                nd.setQuyen(1);
            } else {
                nd.setQuyen(2);
            }
//            nd.setQuyen(rdoUser.isSelected() ? 1 : 2);
            if (rdoNam.isSelected()) {
                nd.setGioiTinh("Nam");
            } else if (rdoNu.isSelected()) {
                nd.setGioiTinh("Nu");
            } else {
                nd.setGioiTinh("Gioi tinh khac");
            }
//            nd.setGioiTinh(rdoNam.isSelected() ? "Nam" 
//                    : rdoNu.isSelected() ? "Nu" : "Gioi tinh khac");
             nd.setTrangThai(chkTrangThai.isSelected());
             
             nd.setViTriCV(cboViTriCv.getSelectedItem().toString());
             
             return nd;
     }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QLND.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QLND.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QLND.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QLND.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QLND().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btnGGioiTinh;
    private javax.swing.ButtonGroup btnGRole;
    private javax.swing.JButton btnNhap;
    private javax.swing.JButton btnSapXep;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnTim;
    private javax.swing.JButton btnXoa;
    private javax.swing.JButton btnXuat;
    private javax.swing.JComboBox<String> cboViTriCv;
    private javax.swing.JCheckBox chkTrangThai;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rdoAdmin;
    private javax.swing.JRadioButton rdoKhac;
    private javax.swing.JRadioButton rdoNam;
    private javax.swing.JRadioButton rdoNu;
    private javax.swing.JRadioButton rdoUser;
    private javax.swing.JTable tblListND;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtMatKhau;
    private javax.swing.JTextField txtTaiKhoan;
    // End of variables declaration//GEN-END:variables
}
